# i18n
timezone: America/Sao_Paulo
language: pt
i18n:
  type: [page, post]
  generator: [category, tag, index]

# URL
url: https://wiki.jhow.io
repo: https://github.com/jonathan-santos/wikijhow
root: /
permalink: :lang/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
category_dir: categories
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:title.md
default_layout: post
titlecase: false
external_link:
  enable: true
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
  
# Category & Tag
default_category: uncategorized

# Date / Time format
date_format: DD/MM/YYYY
time_format: HH:mm:ss

# Pagination
per_page: 0

# Syntax Highlighting
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true

# Extensions
theme: hexo-jhow-theme
theme_config:
  wikiMode: true
  noFaq: true
  primaryColor: '#8be9fd'
  secondaryColor: '#ff2d9a'
